apiVersion: apps/v1
kind: Deployment
metadata:
  name: anand
  namespace: anand
spec:
  selector:
    matchLabels:
      app: anand
  template:
    metadata:
      labels:
        app: anand
    spec:
      containers:
      - name: petclinic
        image: 288701581823.dkr.ecr.ap-northeast-1.amazonaws.com/test:5
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: DB_USER_URL
          valueFrom:
            configMapKeyRef:
              name: anandconfigmap
              key: URL
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: anandsecret
              key: USER_NAME
        - name: DB_USER_PASSWD
          valueFrom:
            secretKeyRef:
              name: anandsecret
              key: PASSWORD 
        ports:
        - containerPort: 8080