apiVersion: v1
kind: PersistentVolume
metadata:
  name: anandpv
  namespace: anand
spec:
  capacity:
    storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2


# (or)

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv
# spec:
#   accessModes:
#   - ReadWriteOnce
#   awsElasticBlockStore:
#     fsType: xfs
#     volumeID: aws://us-east-1a/vol-xxxxxxxxxxxx
#   capacity:
#     storage: 10Gi
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: gp2-retain
#   volumeMode: Filesystem
