apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anandpvc
  namespace: anand
spec:
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
