apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anandpvc
  namespace: anand
spec:
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: mysql
#   name: pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: gp2-retain
#   volumeMode: Filesystem
#   volumeName: pv
